[features]
seeds = false
skip-lint = false
[programs.mainnet]
breadheads = "E8D44KvNHsDZDxpUkaYo8yZgraQNBgCdXcD7jwJRTF3K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
